# Generated by Django 3.2.8 on 2022-05-02 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
